### ISSUE TITLE
change `variant.match: Array<string>` to `variant.match: Record<string, string>`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#111]
### Context

Variants with a positional match value will lead broken matches that can't be fixed with lint rules.

Variants have a match array. The order of the values in the match array determines how variants are matched. Unfortunately, the matching order depends on the messages selector order.

Any change in the message's selection order needs to update all variants (💥). There is no guarantee that applications, developers, or users will remember to update the order of all variants. Lint rules are not able to fix the ordering without a history API. Any match value could be correctly positioned.

*Message*

```
{
  id: ...,
  locale: ...,
  declarations: ...,
  selectors: [
    {
      type: "expression",
      arg: {
        type: "variable",
        name: "numProducts",
      },
      annotation: {},
    },
    {
      type: "expression",
      arg: {
        type: "variable",
        name: "username",
      },
      annotation: {},
    },
  ]
}
```

*Variant*

```
{
  id: ...
  // is zero matching for username or numProducts?
  match: ["zero", "many"],
  pattern: ...
};
```

### Proposal

Turn `match` into a Record<string, string> and eliminate the necessity to keep the positioning of `message.selectors` and `variant.match` in sync. 

```diff
{
  id: ...
-  match: ["zero", "many"],
+  match: { username: "many", numProducts: "zero"  }
  pattern: ...
};
```

The danger of a matching key not being defined in `message.selectors` or `variant.match` can be mitigated with a lint rule: 

> "The matching key 'username' does not exist in the message selector" -> \`fix(\[removeMatchFromVariant, createSelector\])\`

**Comment by samuelstroschein** [comment]
came up in a chat with @martin.lysk1 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/bad356a1-a491-48be-a231-1e40fb6d94b1/81b243f7-0eea-48fd-8311-b324dedfb7b2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iYWQzNTZhMS1hNDkxLTQ4YmUtYTIzMS0xZTQwZmI2ZDk0YjEvODFiMjQzZjctMGVlYS00OGZkLTgzMTEtYjMyNGRlZGZiN2IyIiwiaWF0IjoxNzIwMzkwNjM1LCJleHAiOjMzMjkwOTUwNjM1fQ.E3v4PRUTpFQZg6jLGSa5HYqk0G1DR2vn35r15K3ZH2g " alt="CleanShot 2024-07-07 at 18.16.43@2x.png" width="1776" height="444" />

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/2291c985-30d1-4a9c-9c0b-c88bc47f00ec/2e5cff7a-b3b4-4a4f-92bc-f41d87991750?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yMjkxYzk4NS0zMGQxLTRhOWMtOWMwYi1jODhiYzQ3ZjAwZWMvMmU1Y2ZmN2EtYjNiNC00YTRmLTkyYmMtZjQxZDg3OTkxNzUwIiwiaWF0IjoxNzIwMzkwNjM1LCJleHAiOjMzMjkwOTUwNjM1fQ.MDxQtlqiPbn0E86vk6oq751PdQLntAeLUpH7sUNB9gY " alt="CleanShot 2024-07-07 at 18.17.06@2x.png" width="1462" height="374" />

**Comment by martin-lysk** [comment]
This one is a rabbit whole 🙁 And needs more research:

Good readings:<br>[https://github.com/aphillips/message-format-wg/blob/main/exploration/selection-matching-options.md](https://github.com/aphillips/message-format-wg/blob/main/exploration/selection-matching-options.md)

Still trying to understand the reasoning behind this one better:<br>[https://github.com/aphillips/message-format-wg/blob/main/spec/formatting.md#example-2](https://github.com/aphillips/message-format-wg/blob/main/spec/formatting.md#example-2)

Seems like the order of variants withinin a message also is taken into account here - got to check if we need to take this into account somehow:<br>[https://github.com/aphillips/message-format-wg/blob/main/spec/formatting.md#sort-variants](https://github.com/aphillips/message-format-wg/blob/main/spec/formatting.md#sort-variants)

Some more readings - that may help:

[https://github.com/unicode-org/message-format-wg/blob/4de2684f4caa52cafca2d80116f9dd24a513bf89/meetings/2023/notes-2023-03-13.md?plain=1#L111](https://github.com/unicode-org/message-format-wg/blob/4de2684f4caa52cafca2d80116f9dd24a513bf89/meetings/2023/notes-2023-03-13.md?plain=1#L111)

[https://github.com/unicode-org/message-format-wg/issues/351](https://github.com/unicode-org/message-format-wg/issues/351)

[https://github.com/aphillips/message-format-wg/blob/main/exploration/selection-matching-options.md](https://github.com/aphillips/message-format-wg/blob/main/exploration/selection-matching-options.md)

Why this is important? 

If we change like suggested:

```
{
  id: ...
-  match: ["zero", "many"],
+  match: { likes: "many", shares: "zero"  }
  pattern: ...
};
```

This changes - "changes" on an atom variant since we loose the order information on match - that was there before. an alternative would be:

```
{
  id: ...
-  match: ["zero", "many"],
+  match: [{shares: "zero" }, { likes: "many" }]
  pattern: ...
};
```

Lets play through the possible scenarios based on those variants:

## **Selector Inserted:**

\[likes, numProducts\] -> \[gender, userName, numProducts\]

macht of all variants need to be updated - linting not possible:

```
[*, zero, many] -> variant A
[*, zero, *]    -> variant B
[*, *,    *]    -> variant C
```

**Proposed model**

```
{ likes: zero, numProducts: many } -> variant A
{ likes: zero, numProducts: * }    -> variant B
{ likes: *, numProducts: * }    -> variant C
```

Linting Possible - no direct action on each variant needed:

After lints are fixed - all messages receive a change

```
{ gender: *, likes: zero, numProducts: many } -> variant A
{ gender: *, likes: zero, numProducts: * }    -> variant B
{ gender: *, likes: *, numProducts: * }    -> variant C
```

Proposed model with sort - all message receive a change

```
[{ gender: *},{ likes: zero},{ numProducts: many }] -> variant A
[{ gender: *},{ likes: zero},{ numProducts: * }]    -> variant B
[{ gender: *},{ likes: *},{ numProducts: many }]    -> variant C
```

# **Selector Renamed:**

\[likes, numProducts\] -> \[numLikes, numProducts\]

```
[zero, many] -> variant A
[zero, *]    -> variant B
[*,    *]    -> variant C
```

no change the variants (wanted?)

**Proposed model**

```
{ likes: zero, numProducts: many } -> variant A
{ likes: zero, numProducts: * }    -> variant B
{ likes: *, numProducts: * }    -> variant C
```

Lints trigger

**Selector Moved:**

\[likes, numProducts\] -> \[numProducts, likes\]

```
[zero, many] -> variant A
[zero, *]    -> variant B
[*,    *]    -> variant C
```

all variants need to be updated:

```
[many, zero] -> variant A
[*, zero]    -> variant B
[*,    *]    -> variant C
```

**Comment by martin-lysk** [comment]
@nils.jacobsen this also impacts the bundle component!

**Comment by NilsJacobsen** [comment]
@martin.lysk1 

> we cant match matchers to selectors afterwards -> match of all variants need to be updated in one transaction - not possible via linting:

That seems to be the main probelm right? Can you explain a bit more what causes the issue in detail?

**Comment by martin-lysk** [comment]
In the current approach we don't have a reference to the selectors other than order in the matchers. As soon as the list ant the position of its elements change (this happens on moving selectors, inserting, and deleting (not renaming)) you loose the connection between a selector and a matcher within the match array of the variant.

This means you have to update all variants in the same transaction as the message(with the new selectors). <br><br>In a distributed system this can only be enforced if we define a Message as an atom and expect those cases to be dealt with during merge.

**Comment by NilsJacobsen** [comment]
I thought a message is already a atom?

**Comment by martin-lysk** [comment]
Nope - that was how it was modelled in the rxdb/slot storage setup - now we have a varaint table

**Comment by NilsJacobsen** [comment]
Ahh we bundle and variant now? Or just variants?

**Comment by NilsJacobsen** [comment]
let's sync in around

**Comment by samuelstroschein** [comment]
@martin.lysk1 thanks for the detailed write up. as discussed on call, i would choose option B.

1. taking positioning out of matchers makes variants simpler and leads to no change if the position changes.
2. atomicy" is not a concern of inlang but lix<br><br>Lix needs to work irrespective of how apps define their data structures. Otherwise, lix is not generalizable. Lix must be able to raise a merge conflict if "actor A added a new variant and actor B changed the matching order on a message".   

```diff
{
  id: ...
+  match: { username: "many", numProducts: "zero"  }
  pattern: ...
};
```

**Comment by NilsJacobsen** [comment]
Isn't the problem that, since we don't have a gatekeeper that allows us to do an addSelector mutation (update message, updateVariants, insertVariants), we need to process that user interaction in multiple transactions? That means Lix might raise a conflict while processing these transactions. Even though they get resolved after the last one. 

Maybe I got it wrong :D

**Comment by samuelstroschein** [comment]
I don't understand what you mean with transaction. Loom maybe?

**Comment by NilsJacobsen** [comment]
Little update: [https://www.loom.com/share/e62f523855c1437b82d13b27f7349be3](https://www.loom.com/share/e62f523855c1437b82d13b27f7349be3)<br><br>**TL;DR:**

* I added the new type and adjusted all test in the sdk-v2 and component
* Duplicate selectors are not possible anymore
* We might handle too many or less matchers in variant

**Comment by samuelstroschein** [comment]
@nils.jacobsen any problem that arises should be fixable by lint rules. if a matcher does not exist for a variant, there -should- will be a lint rule that detects the error

**Comment by martin-lysk** [comment]
I sketched down the cases that we could face with one variant. 

We will need to be able to visualize those cases in the UI somehow and provide a mechanism for each - case.

1. A new selector "newSelector" has been added to the message which the variant does have yet.
   1. Lint fix -> add missing matcher
   2. ui -> show an empty field for the matcher in the variant
2. The name of the selector has changed for "newName",
   1. Lint fix -> ? 
   2. ui -> add a column for "oldName" selector?
3. The Variant contains a matcher that the message does not know.
   1. Lint fix 1 -> add selector (we only have the name of the selector not the type, arg etc)
   2. Lint fix 2 -> remove the matcher without selector from the variant
   3. UI -> add a column for "nonExistingSelector" selector?

```
{
    "id": "keen_next_deer_charm",
    "alias": {
        "default": "name_steep_direct_walrus_surge"
    },
    "messages": [
        {
            "id": "09e31f50-a3d7-47cd-b9e2-1b44231b5ab1",
            "bundleId": "keen_next_deer_charm",
            "locale": "en",
            ...
            "selectors": [
                {
                    "type": "expression",
                    "arg": {
                        "type": "variable",
                        "name": "newName"
                    },
                    ...
                },
                {
                    "type": "expression",
                    "arg": {
                        "type": "variable",
                        "name": "newSelector"
                    },
                    ...
                },
                
            ],
            "variants": [
                {
                    "id": "c3ee4b64-80d5-4a40-95df-376ef54b7ca8",
                    "match": {
                        "oldName": "other",
                        "nonExistingSelector": "other"
                    },
                    "pattern": [
                        {
                            "type": "text",
                            "value": "Welcome user!"
                        }
                    ]
                },
                
                
            ]
        }
    ]
} 
```

**Comment by samuelstroschein** [comment]
> We will need to be able to visualize those cases in the UI somehow and provide a mechanism for each - case.

Lix inlang plugin will have a differ 😎

**Comment by martin-lysk** [comment]
No further action required for now
