### ISSUE TITLE
remove `addCustomApi` for a static prop

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#125]
### Context

The resolving logic for plugins becomes easier/not required if `addCustomAPi` is not a runtime function but static prop.

### Proposal

Add a static meta field as replacement for `addCustomApi`.

* nested under meta to avoid collisions if we add more APIs to a plugin

```diff
const plugin = {
  key: "i18next",
  importFiles,
  exportFiles,
- addCustomApi()
+ meta: {
+ functionMatch()
+ documentPaths: ["*.json"]
+ }
}
```

Nesting namespaces is possible too

```diff
const plugin = {
  key: "i18next",
  importFiles, 
  exportFiles, 
  meta: {
+    'app.inlang.sherlock': {
+       documentPaths: ["*.json"]
+     }
  }
}
```

An app like Sherlock could use the API like

```
const plugins = project.plugins.find((p) => p.meta['app.inlang.sherlock')
const documenPaths = plugins.map((p) => p.meta['app.inlang.sherlock'].documentPaths)
```

cc @felix.haeberle

**Comment by samuelstroschein** [comment]
@felix.haeberle is this done?

**Comment by samuelstroschein** [comment]
wondering if i can close this issue

**Comment by felixhaeberle** [comment]
this is done referring to the types being adjusted in the SDK v2. <br><br>what hasn't been done is verify in Sherlock if this is actually working because of project loading bugs I currently encounter. there is furthermore currently no backwards compatible code in Sherlock, means that it currently doesnt respect `customApi` anymore. <br>this will change in: [SHERL-99](https://linear.app/opral/issue/SHERL-99/add-backwards-compat-in-sherlock-for-sdk-v1-and-v2)<br><br>also not done: changing this in all plugins for the next, "sdk v2 compatible" versions. I guess we can close this but def have to do follow-ups.
